import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header
          className="w-full h-[90px] flex items-center justify-center"
          style={{
            position: "relative",
            backgroundImage: "url(/images/abstract-square-houses.png)",
            backgroundSize: "60% 400px",
            backgroundRepeat: "repeat",
            backgroundPosition: "center",
          }}
        >
          <div className="bg-black/50 rounded-lg backdrop-blur-sm shadow-[0_10px_30px_rgba(0,0,0,0.3),0_4px_8px_rgba(0,0,0,0.2)] hover:shadow-[0_20px_40px_rgba(0,0,0,0.4),0_8px_16px_rgba(0,0,0,0.3)] transition-shadow duration-300">
            <h1 className="text-3xl font-bold text-white relative px-6 py-3 rounded-lg">
              Real Estate AI Marketing Suite
            </h1>
          </div>
        </header>
        <main className="flex flex-col gap-[32px] items-center w-full">
          {children}
        </main>
      </body>
    </html>
  );
}
